// Aritmética computacional / representação numérica.
// Fonte: Lista1_AC2_Teoria, slides_aritmetica, guia.
export default [
  {
    id: "arit.bases.hexvalido.001",
    topico: "Aritmética Computacional",
    subtopico: "Bases numéricas",
    dificuldade: 1,
    tipo: "single-choice",
    tags: ["hexadecimal", "bases"],
    enunciado: "Qual destas 'palavras' NÃO é um número hexadecimal válido?",
    contexto: "Dígitos hex válidos: 0-9 e A-F.",
    opcoes: [
      { id: "a", label: "FACA" },
      { id: "b", label: "CABO" },
      { id: "c", label: "DAD" },
      { id: "d", label: "FADA" },
    ],
    resposta: "b",
    explicacao: "CABO contém 'O', que não é dígito hexadecimal (vai só até F). As demais usam só A-F.",
    porqueErros: {
      a: "FACA usa F, A, C, A — todos válidos.",
      c: "DAD usa D, A, D — válidos.",
      d: "FADA usa F, A, D, A — válidos.",
    },
    fonte: { material: "lista1_teoria", capitulo: "Q1" },
    tempoEstimado: 20,
  },
  {
    id: "arit.conv.decbin.001",
    topico: "Aritmética Computacional",
    subtopico: "Conversão de bases",
    dificuldade: 2,
    tipo: "numeric",
    tags: ["conversão", "binário"],
    enunciado: "Converta (1984)₁₀ para binário. (responda em base 2)",
    resposta: { valor: 1984, base: 2, tolerancia: 0 },
    explicacao: "1984 = 1024+512+256+128+64 = 11111000000₂.",
    fonte: { material: "lista1_teoria", capitulo: "Q2a" },
    tempoEstimado: 60,
  },
  {
    id: "arit.frac.bin.001",
    topico: "Aritmética Computacional",
    subtopico: "Ponto fixo fracionário",
    dificuldade: 3,
    tipo: "numeric",
    tags: ["fração", "binário"],
    enunciado: "Quanto vale (11011,101)₂ em decimal?",
    contexto: "Parte inteira + frações: 2⁻¹=0,5 · 2⁻²=0,25 · 2⁻³=0,125",
    resposta: { valor: 27.625, base: 10, tolerancia: 0.001 },
    explicacao: "11011₂ = 27. Parte fracionária ,101 = 0,5 + 0 + 0,125 = 0,625. Total = 27,625.",
    fonte: { material: "lista1_teoria", capitulo: "Q6a" },
    tempoEstimado: 90,
  },
  {
    id: "arit.soma.hex.001",
    topico: "Aritmética Computacional",
    subtopico: "Operações em hexadecimal",
    dificuldade: 3,
    tipo: "single-choice",
    tags: ["hexadecimal", "soma"],
    enunciado: "Quanto é (4A3)₁₆ + (D13)₁₆ ?",
    opcoes: [
      { id: "a", label: "11B6₁₆" },
      { id: "b", label: "1196₁₆" },
      { id: "c", label: "11A6₁₆" },
      { id: "d", label: "D1B6₁₆" },
    ],
    resposta: "a",
    explicacao: "4A3₁₆=1187, D13₁₆=3347, soma=4534 = 11B6₁₆.",
    porqueErros: {
      b: "Esqueceu o vai-um na soma dos dígitos do meio.",
      c: "Erro no dígito 'B' (A+1 com carry).",
      d: "Não houve estouro mantendo D no topo; há propagação de carry.",
    },
    fonte: { material: "lista1_teoria", capitulo: "Q5a" },
    tempoEstimado: 60,
  },
  {
    id: "arit.overflow.001",
    topico: "Aritmética Computacional",
    subtopico: "Overflow (complemento de 2)",
    dificuldade: 4,
    tipo: "single-choice",
    tags: ["overflow", "complemento-2"],
    enunciado: "Em complemento de 2, como se detecta overflow numa soma?",
    opcoes: [
      { id: "a", label: "XOR entre o carry de entrada e o carry de saída do bit mais significativo" },
      { id: "b", label: "Quando o bit menos significativo do resultado é 1" },
      { id: "c", label: "Quando há qualquer carry out" },
      { id: "d", label: "Quando os dois operandos têm sinais diferentes" },
    ],
    resposta: "a",
    explicacao: "Overflow = XOR(Cin_MSB, Cout_MSB). Se o carry que entra no bit de sinal difere do que sai, houve estouro.",
    porqueErros: {
      b: "O bit menos significativo não tem relação com overflow.",
      c: "Carry out sozinho não indica overflow em complemento de 2.",
      d: "Somar sinais diferentes nunca causa overflow; o problema é somar sinais iguais.",
    },
    fonte: { material: "gabarito_prova", capitulo: "P2" },
    tempoEstimado: 45,
  },
];
