// Somador Carry-Lookahead (CLA).
// Fonte: slides_cla, Lista1 Q10, gabarito_prova P1, guia.
export default [
  {
    id: "cla.gerador.001",
    topico: "Somador CLA",
    subtopico: "Gerador e Propagador",
    dificuldade: 2,
    tipo: "single-choice",
    tags: ["CLA", "gerador"],
    enunciado: "No CLA, o sinal Gerador (Gᵢ) é definido como:",
    opcoes: [
      { id: "a", label: "Gᵢ = Aᵢ · Bᵢ  (AND)" },
      { id: "b", label: "Gᵢ = Aᵢ + Bᵢ  (OR)" },
      { id: "c", label: "Gᵢ = Aᵢ ⊕ Bᵢ  (XOR)" },
      { id: "d", label: "Gᵢ = NOT Aᵢ" },
    ],
    resposta: "a",
    explicacao: "Gera um carry por conta própria quando ambos são 1 → Gᵢ = Aᵢ AND Bᵢ.",
    porqueErros: {
      b: "Aᵢ + Bᵢ é o Propagador (P), não o Gerador.",
      c: "XOR também serve como Propagador, não como Gerador.",
      d: "Negação não tem papel na geração de carry.",
    },
    fonte: { material: "slides_cla", capitulo: "Gerador/Propagador" },
    tempoEstimado: 30,
  },
  {
    id: "cla.propagador.001",
    topico: "Somador CLA",
    subtopico: "Gerador e Propagador",
    dificuldade: 2,
    tipo: "single-choice",
    tags: ["CLA", "propagador"],
    enunciado: "O Propagador (Pᵢ) propaga um carry que já existe. Ele é:",
    opcoes: [
      { id: "a", label: "Pᵢ = Aᵢ + Bᵢ  (OR)" },
      { id: "b", label: "Pᵢ = Aᵢ · Bᵢ  (AND)" },
      { id: "c", label: "Pᵢ = 0 sempre" },
      { id: "d", label: "Pᵢ = Cᵢ" },
    ],
    resposta: "a",
    explicacao: "Pᵢ = Aᵢ OR Bᵢ (ou XOR) — se ao menos um bit é 1, um carry de entrada se propaga.",
    porqueErros: {
      b: "AND é o Gerador (G).",
      c: "Seria um propagador inútil.",
      d: "Pᵢ depende de A e B, não do carry de entrada.",
    },
    fonte: { material: "slides_cla", capitulo: "Gerador/Propagador" },
    tempoEstimado: 30,
  },
  {
    id: "cla.carry.c2.001",
    topico: "Somador CLA",
    subtopico: "Equações de carry",
    dificuldade: 4,
    tipo: "single-choice",
    tags: ["CLA", "carry"],
    enunciado: "Qual a expressão correta de C₂ no CLA?",
    contexto: "Cᵢ₊₁ = Gᵢ + Pᵢ·Cᵢ, expandido.",
    opcoes: [
      { id: "a", label: "C₂ = G₁ + P₁·G₀ + P₁·P₀·C₀" },
      { id: "b", label: "C₂ = G₁ + G₀ + C₀" },
      { id: "c", label: "C₂ = P₁·P₀·C₀" },
      { id: "d", label: "C₂ = G₁ · P₀ · C₀" },
    ],
    resposta: "a",
    explicacao: "Expandindo C₂ = G₁ + P₁·C₁ e C₁ = G₀ + P₀·C₀ → C₂ = G₁ + P₁·G₀ + P₁·P₀·C₀.",
    porqueErros: {
      b: "Faltam os propagadores multiplicando os termos.",
      c: "Esse é só o termo do carry inicial; faltam G₁ e P₁·G₀.",
      d: "Os termos são somados (OR), não todos multiplicados.",
    },
    fonte: { material: "guia", capitulo: "CLA" },
    tempoEstimado: 75,
  },
  {
    id: "cla.carryout.001",
    topico: "Somador CLA",
    subtopico: "Vai-um de bloco",
    dificuldade: 3,
    tipo: "single-choice",
    tags: ["CLA", "carry-out", "16-bits"],
    enunciado: "Em 16 bits, a soma (3AF1)₁₆ + (45EA)₁₆ gera vai-um (carry out)?",
    opcoes: [
      { id: "a", label: "Não — o resultado cabe em 16 bits" },
      { id: "b", label: "Sim — estoura 16 bits" },
    ],
    resposta: "a",
    explicacao: "3AF1₁₆=15089, 45EA₁₆=17898, soma=32987 < 65536 (2¹⁶). Logo não há carry out.",
    porqueErros: {
      b: "32987 ainda cabe em 16 bits (< 65536); não estoura.",
    },
    fonte: { material: "gabarito_prova", capitulo: "Q10b" },
    tempoEstimado: 60,
  },
];
