// ISA / Linguagem de máquina MIPS.
// Fonte: slides_mips_intro, slides_mips_maquina.
export default [
  {
    id: "isa.formato-r.opcode.001",
    topico: "ISA / Linguagem de Máquina",
    subtopico: "Formatos de instrução",
    dificuldade: 2,
    tipo: "single-choice",
    tags: ["formato-R", "opcode"],
    enunciado: "No formato R do MIPS (32 bits), quantos bits tem o campo opcode?",
    contexto: "Formato R: opcode | rs | rt | rd | shamt | funct",
    opcoes: [
      { id: "a", label: "6" },
      { id: "b", label: "5" },
      { id: "c", label: "16" },
      { id: "d", label: "26" },
    ],
    resposta: "a",
    explicacao: "opcode=6, rs=5, rt=5, rd=5, shamt=5, funct=6 → 32 bits. O opcode tem 6 bits.",
    porqueErros: {
      b: "5 bits é o tamanho dos campos de registrador (rs, rt, rd).",
      c: "16 bits é o imediato do formato I.",
      d: "26 bits é o endereço do formato J.",
    },
    fonte: { material: "slides_mips_maquina", capitulo: "Formato R" },
    tempoEstimado: 40,
  },
  {
    id: "isa.lw.formato.001",
    topico: "ISA / Linguagem de Máquina",
    subtopico: "Formatos de instrução",
    dificuldade: 2,
    tipo: "single-choice",
    tags: ["lw", "formato-I"],
    enunciado: "A instrução lw (load word) pertence a qual formato?",
    opcoes: [
      { id: "a", label: "Formato I (imediato)" },
      { id: "b", label: "Formato R" },
      { id: "c", label: "Formato J" },
      { id: "d", label: "Nenhum, é pseudo-instrução" },
    ],
    resposta: "a",
    explicacao: "lw usa base+deslocamento: opcode|rs|rt|imediato(16) → formato I.",
    porqueErros: {
      b: "Formato R é para operações registrador-registrador (add, sub…).",
      c: "Formato J é para saltos (j, jal).",
      d: "lw é uma instrução real do MIPS.",
    },
    fonte: { material: "slides_mips_maquina", capitulo: "Formato I" },
    tempoEstimado: 30,
  },
  {
    id: "isa.zero.001",
    topico: "ISA / Linguagem de Máquina",
    subtopico: "Registradores",
    dificuldade: 1,
    tipo: "single-choice",
    tags: ["registradores", "zero"],
    enunciado: "Qual registrador do MIPS contém sempre o valor 0?",
    opcoes: [
      { id: "a", label: "$zero ($0)" },
      { id: "b", label: "$ra ($31)" },
      { id: "c", label: "$sp ($29)" },
      { id: "d", label: "$v0 ($2)" },
    ],
    resposta: "a",
    explicacao: "$zero ($0) é fixo em 0, útil para comparações e mover valores.",
    porqueErros: {
      b: "$ra guarda o endereço de retorno.",
      c: "$sp é o ponteiro de pilha.",
      d: "$v0 guarda valores de retorno de função.",
    },
    fonte: { material: "slides_mips_intro", capitulo: "Registradores" },
    tempoEstimado: 20,
  },
  {
    id: "isa.shift.mult.001",
    topico: "ISA / Linguagem de Máquina",
    subtopico: "Shifts e aritmética",
    dificuldade: 2,
    tipo: "single-choice",
    tags: ["shift", "sll"],
    enunciado: "Como multiplicar um registrador por 4 usando deslocamento?",
    opcoes: [
      { id: "a", label: "sll $x, $x, 2   (shift left 2)" },
      { id: "b", label: "srl $x, $x, 2   (shift right 2)" },
      { id: "c", label: "sll $x, $x, 4" },
      { id: "d", label: "sra $x, $x, 2" },
    ],
    resposta: "a",
    explicacao: "Deslocar à esquerda n bits multiplica por 2ⁿ. ×4 = 2² → sll de 2.",
    porqueErros: {
      b: "Shift à direita DIVIDE, não multiplica.",
      c: "Deslocar 4 multiplica por 16, não 4.",
      d: "sra é shift à direita aritmético (divide com sinal).",
    },
    fonte: { material: "slides_mips_maquina", capitulo: "Shifts" },
    tempoEstimado: 40,
  },
];
