// Hierarquia de memória e cache.
// Fonte: slides_memoria, guia.
export default [
  {
    id: "mem.cache.tecnologia.001",
    topico: "Memória e Cache",
    subtopico: "Tecnologias de memória",
    dificuldade: 1,
    tipo: "single-choice",
    tags: ["cache", "sram", "dram"],
    enunciado: "Qual tecnologia é usada na memória cache, por ser mais rápida?",
    opcoes: [
      { id: "a", label: "SRAM" },
      { id: "b", label: "DRAM" },
      { id: "c", label: "Disco rígido (HD)" },
      { id: "d", label: "Flash NAND" },
    ],
    resposta: "a",
    explicacao: "SRAM é rápida (sem refresh) e cara → usada na cache. DRAM é mais lenta/barata → RAM principal.",
    porqueErros: {
      b: "DRAM precisa de refresh e é mais lenta; é a RAM principal.",
      c: "HD é armazenamento secundário, ordens de grandeza mais lento.",
      d: "Flash é não-volátil e lenta para uso como cache.",
    },
    fonte: { material: "slides_memoria", capitulo: "Hierarquia" },
    tempoEstimado: 30,
  },
  {
    id: "mem.ddr.001",
    topico: "Memória e Cache",
    subtopico: "RAM / DDR",
    dificuldade: 2,
    tipo: "single-choice",
    tags: ["ddr", "ram"],
    enunciado: "Quantos dados a memória DDR transmite por ciclo de clock?",
    opcoes: [
      { id: "a", label: "2 (na subida e na descida do clock)" },
      { id: "b", label: "1" },
      { id: "c", label: "4" },
      { id: "d", label: "8" },
    ],
    resposta: "a",
    explicacao: "DDR = Double Data Rate: transfere 2 dados por ciclo (bordas de subida e descida).",
    porqueErros: {
      b: "1 por ciclo seria SDR (single data rate).",
      c: "4 seria uma interpretação de DDR4 por outros fatores, não 'por ciclo'.",
      d: "8 não corresponde ao princípio DDR básico.",
    },
    fonte: { material: "slides_memoria", capitulo: "DIMM/DDR" },
    tempoEstimado: 30,
  },
  {
    id: "mem.hamming.001",
    topico: "Memória e Cache",
    subtopico: "Código de Hamming",
    dificuldade: 3,
    tipo: "single-choice",
    tags: ["hamming", "erro"],
    enunciado: "No código de Hamming (7,4) — 4 bits de dados — quantos bits de verificação são usados?",
    contexto: "Regra: 2ʳ ≥ m + r + 1, com m = bits de dados.",
    opcoes: [
      { id: "a", label: "3" },
      { id: "b", label: "2" },
      { id: "c", label: "4" },
      { id: "d", label: "7" },
    ],
    resposta: "a",
    explicacao: "Com m=4: 2³=8 ≥ 4+3+1=8 ✓. Logo r=3 bits de verificação (total 7 bits).",
    porqueErros: {
      b: "Com r=2: 2²=4 < 4+2+1=7. Insuficiente.",
      c: "r=4 funcionaria mas é mais do que o necessário; (7,4) usa 3.",
      d: "7 é o total de bits, não os de verificação.",
    },
    fonte: { material: "slides_memoria", capitulo: "Hamming" },
    tempoEstimado: 60,
  },
  {
    id: "mem.hd.latencia.001",
    topico: "Memória e Cache",
    subtopico: "Disco rígido",
    dificuldade: 2,
    tipo: "single-choice",
    tags: ["hd", "latencia"],
    enunciado: "A latência rotacional MÉDIA de um HD corresponde ao tempo de quantas rotações?",
    opcoes: [
      { id: "a", label: "Meia rotação (½)" },
      { id: "b", label: "Uma rotação completa" },
      { id: "c", label: "Duas rotações" },
      { id: "d", label: "Um quarto de rotação (¼)" },
    ],
    resposta: "a",
    explicacao: "Em média o setor desejado está a meia volta de distância → latência média = (60/RPM)/2.",
    porqueErros: {
      b: "Uma rotação completa é o pior caso, não a média.",
      c: "Duas rotações não faz sentido físico para latência.",
      d: "Meia volta é a média estatística, não um quarto.",
    },
    fonte: { material: "slides_memoria", capitulo: "HD" },
    tempoEstimado: 45,
  },
];
