// Lei de Amdahl.
// Fonte: slides_amdahl, gabarito_prova (Q20-Q24, P4-P6), guia.
export default [
  {
    id: "amdahl.formula.001",
    topico: "Lei de Amdahl",
    subtopico: "Conceito",
    dificuldade: 1,
    tipo: "single-choice",
    tags: ["amdahl", "speedup"],
    enunciado: "A Lei de Amdahl diz que o speedup global é:",
    contexto: "f = fração do tempo melhorada; k = quanto essa parte ficou mais rápida.",
    opcoes: [
      { id: "a", label: "1 / [ (1−f) + f/k ]" },
      { id: "b", label: "k · f" },
      { id: "c", label: "1 / (f · k)" },
      { id: "d", label: "(1−f) + f·k" },
    ],
    resposta: "a",
    explicacao: "Só a fração f é acelerada k vezes; o resto (1−f) continua igual. Speedup = 1/[(1−f)+f/k].",
    porqueErros: {
      b: "Ignora a parte não acelerada (1−f).",
      c: "Inverte a lógica; o denominador correto soma as duas frações.",
      d: "Isso seria um tempo, e ainda com k no lugar errado.",
    },
    fonte: { material: "slides_amdahl", capitulo: "Fórmula" },
    tempoEstimado: 30,
  },
  {
    id: "amdahl.cache.001",
    topico: "Lei de Amdahl",
    subtopico: "Cálculo de speedup",
    dificuldade: 3,
    tipo: "numeric",
    tags: ["amdahl", "cache"],
    enunciado: "Uma cache 5× mais rápida é usada 90% do tempo. Qual o speedup global? (1 casa)",
    resposta: { valor: 3.57, base: 10, tolerancia: 0.06 },
    explicacao: "Speedup = 1/(0,1 + 0,9/5) = 1/0,28 ≈ 3,57×.",
    fonte: { material: "gabarito_prova", capitulo: "Q20" },
    tempoEstimado: 75,
  },
  {
    id: "amdahl.copro.001",
    topico: "Lei de Amdahl",
    subtopico: "Cálculo de speedup",
    dificuldade: 2,
    tipo: "numeric",
    tags: ["amdahl"],
    enunciado: "Um coprocessador 5× mais rápido acelera 50% do tempo. Speedup global?",
    resposta: { valor: 1.67, base: 10, tolerancia: 0.05 },
    explicacao: "Speedup = 1/(0,5 + 0,5/5) = 1/0,6 ≈ 1,67×.",
    fonte: { material: "gabarito_prova", capitulo: "Q21a" },
    tempoEstimado: 60,
  },
  {
    id: "amdahl.limite.001",
    topico: "Lei de Amdahl",
    subtopico: "Limite assintótico",
    dificuldade: 3,
    tipo: "single-choice",
    tags: ["amdahl", "limite"],
    enunciado: "Se apenas f=0,2 do programa pode ser acelerado, qual o speedup MÁXIMO (k→∞)?",
    opcoes: [
      { id: "a", label: "1,25×" },
      { id: "b", label: "5×" },
      { id: "c", label: "Ilimitado" },
      { id: "d", label: "0,8×" },
    ],
    resposta: "a",
    explicacao: "Limite = 1/(1−f) = 1/0,8 = 1,25×. Não importa quão rápida a parte: o resto domina.",
    porqueErros: {
      b: "5× seria o k, não o speedup global.",
      c: "Amdahl impõe um teto: 1/(1−f).",
      d: "0,8 é (1−f); o speedup é o inverso disso.",
    },
    fonte: { material: "slides_amdahl", capitulo: "Limite" },
    tempoEstimado: 45,
  },
];
