// Datapath, sinais de controle e tempos (modelo do professor).
// Tempos: Memória=4, Registradores=1, ULA=2, Controle=1, Somadores=1.
// Caminhos críticos: lw=12, sw=11, R=8, beq=7, j=4. Período uniciclo=12.
// Fonte: slides_datapath, Lista 3.
const SINAIS = [
  { id: "RegDst", label: "RegDst" },
  { id: "ALUSrc", label: "ALUSrc" },
  { id: "MemToReg", label: "MemToReg" },
  { id: "RegWrite", label: "RegWrite" },
  { id: "MemRead", label: "MemRead" },
  { id: "MemWrite", label: "MemWrite" },
  { id: "Branch", label: "Branch" },
];

export default [
  {
    id: "dp.controle.lw.001",
    topico: "Datapath e Controle",
    subtopico: "Sinais de controle",
    dificuldade: 3,
    tipo: "toggle-signals",
    tags: ["controle", "lw"],
    enunciado: "Configure os sinais de controle para a instrução lw $t0, 0($s0).",
    contexto: "lw $t0, 0($s0)",
    opcoes: SINAIS,
    resposta: { RegDst: false, ALUSrc: true, MemToReg: true, RegWrite: true, MemRead: true, MemWrite: false, Branch: false },
    explicacao: "lw lê da memória (MemRead=1), usa o imediato na ULA (ALUSrc=1), escreve em rt (RegDst=0) o dado da memória (MemToReg=1, RegWrite=1).",
    porqueErros: {
      RegDst: "RegDst=1 escolheria rd (formato R); lw usa rt.",
      MemWrite: "MemWrite=1 seria sw — lw NÃO escreve na memória.",
      ALUSrc: "ALUSrc precisa ser 1: a ULA soma base + imediato.",
    },
    fonte: { material: "slides_datapath", capitulo: "Controle" },
    tempoEstimado: 60,
  },
  {
    id: "dp.controle.sw.001",
    topico: "Datapath e Controle",
    subtopico: "Sinais de controle",
    dificuldade: 3,
    tipo: "toggle-signals",
    tags: ["controle", "sw"],
    enunciado: "Configure os sinais de controle para a instrução sw $t0, 0($s0).",
    contexto: "sw $t0, 0($s0)",
    opcoes: SINAIS,
    resposta: { RegDst: false, ALUSrc: true, MemToReg: false, RegWrite: false, MemRead: false, MemWrite: true, Branch: false },
    explicacao: "sw escreve na memória (MemWrite=1), usa imediato na ULA (ALUSrc=1) e NÃO escreve registrador (RegWrite=0). RegDst e MemToReg são indiferentes (use 0).",
    porqueErros: {
      RegWrite: "sw não grava em registrador → RegWrite=0.",
      MemRead: "sw não lê a memória de dados.",
      MemWrite: "MemWrite precisa ser 1 — é o que define o sw.",
    },
    fonte: { material: "slides_datapath", capitulo: "Controle" },
    tempoEstimado: 60,
  },
  {
    id: "dp.controle.beq.001",
    topico: "Datapath e Controle",
    subtopico: "Sinais de controle",
    dificuldade: 3,
    tipo: "toggle-signals",
    tags: ["controle", "beq"],
    enunciado: "Configure os sinais de controle para a instrução beq $t0, $t1, destino.",
    contexto: "beq $t0, $t1, destino",
    opcoes: SINAIS,
    resposta: { RegDst: false, ALUSrc: false, MemToReg: false, RegWrite: false, MemRead: false, MemWrite: false, Branch: true },
    explicacao: "beq só liga Branch=1; a ULA subtrai os registradores (ALUSrc=0) e nada é escrito.",
    porqueErros: {
      Branch: "Branch precisa ser 1 — é um desvio condicional.",
      ALUSrc: "ALUSrc=0: a ULA compara dois registradores, não um imediato.",
      RegWrite: "beq não grava em registrador.",
    },
    fonte: { material: "slides_datapath", capitulo: "Controle" },
    tempoEstimado: 50,
  },
  {
    id: "dp.tempo.lw.001",
    topico: "Tempos",
    subtopico: "Caminho crítico",
    dificuldade: 2,
    tipo: "numeric",
    tags: ["tempo", "lw"],
    enunciado: "Com Memória=4, Reg=1, ULA=2, qual o tempo do caminho crítico do lw (em ns)?",
    contexto: "lw passa por: Mem.Instr + lê Reg + ULA + Mem.Dados + escreve Reg.",
    resposta: { valor: 12, base: 10, tolerancia: 0 },
    explicacao: "lw = 4(instr) + 1(reg) + 2(ULA) + 4(dados) + 1(escrita) = 12 ns.",
    fonte: { material: "slides_datapath", capitulo: "Tempos" },
    tempoEstimado: 60,
  },
  {
    id: "dp.tempo.periodo.001",
    topico: "Tempos",
    subtopico: "Período uniciclo",
    dificuldade: 3,
    tipo: "numeric",
    tags: ["tempo", "periodo"],
    enunciado: "No uniciclo (lw=12, sw=11, R=8, beq=7, j=4), qual o período de clock (ns)?",
    resposta: { valor: 12, base: 10, tolerancia: 0 },
    explicacao: "O clock único deve caber na instrução mais lenta (lw) → período = 12 ns.",
    fonte: { material: "slides_datapath", capitulo: "Tempos" },
    tempoEstimado: 45,
  },
  {
    id: "dp.tempo.gcc.001",
    topico: "Tempos",
    subtopico: "Speedup multiciclo",
    dificuldade: 5,
    tipo: "numeric",
    tags: ["benchmark", "speedup", "gcc"],
    enunciado: "Benchmark GCC (22% lw, 11% sw, 49% R, 16% beq, 2% j). Speedup multiciclo vs uniciclo? (2 casas)",
    contexto: "Uniciclo=12 ns p/ todas. Multiciclo: cada uma leva o próprio tempo (lw12, sw11, R8, beq7, j4).",
    resposta: { valor: 1.34, base: 10, tolerancia: 0.03 },
    explicacao: "Média = 0,22·12+0,11·11+0,49·8+0,16·7+0,02·4 = 8,97 ns. Speedup = 12/8,97 ≈ 1,34×.",
    fonte: { material: "lista3", capitulo: "Q3b" },
    tempoEstimado: 120,
  },
  {
    id: "dp.lenta.001",
    topico: "Tempos",
    subtopico: "Caminho crítico",
    dificuldade: 1,
    tipo: "single-choice",
    tags: ["tempo"],
    enunciado: "Qual instrução é a MAIS LENTA no uniciclo (define o período)?",
    opcoes: [
      { id: "a", label: "lw" },
      { id: "b", label: "beq" },
      { id: "c", label: "add (R)" },
      { id: "d", label: "j" },
    ],
    resposta: "a",
    explicacao: "lw=12 ns é a mais lenta: passa por memória de instrução E de dados, mais ULA e escrita.",
    porqueErros: {
      b: "beq=7 ns (sem acesso à memória de dados).",
      c: "add=8 ns.",
      d: "j=4 ns, a mais rápida.",
    },
    fonte: { material: "slides_datapath", capitulo: "Tempos" },
    tempoEstimado: 25,
  },
];
