// Desempenho: tempo de CPU, CPI, clock, métrica MIPS.
// Fonte: slides_desempenho, Lista1 Q25-Q29, gabarito_prova P7-P12, guia.
export default [
  {
    id: "desemp.equacao.001",
    topico: "Desempenho",
    subtopico: "Equação da CPU",
    dificuldade: 1,
    tipo: "single-choice",
    tags: ["cpu-time", "cpi"],
    enunciado: "A equação fundamental do tempo de CPU é:",
    opcoes: [
      { id: "a", label: "Tempo = IC × CPI × Tempo_de_clock" },
      { id: "b", label: "Tempo = IC + CPI + frequência" },
      { id: "c", label: "Tempo = frequência / CPI" },
      { id: "d", label: "Tempo = CPI / IC" },
    ],
    resposta: "a",
    explicacao: "Tempo_CPU = (nº de instruções) × (ciclos por instrução) × (período de clock).",
    porqueErros: {
      b: "São fatores que se multiplicam, não se somam.",
      c: "Frequência é o inverso do período; a relação não é essa.",
      d: "Inverte os papéis de CPI e IC.",
    },
    fonte: { material: "slides_desempenho", capitulo: "Equação CPU" },
    tempoEstimado: 30,
  },
  {
    id: "desemp.cpimedio.001",
    topico: "Desempenho",
    subtopico: "CPI médio",
    dificuldade: 2,
    tipo: "numeric",
    tags: ["cpi"],
    enunciado: "60% das instruções têm CPI 4 e 40% têm CPI 5. Qual o CPI médio?",
    resposta: { valor: 4.4, base: 10, tolerancia: 0.02 },
    explicacao: "CPI = 0,6×4 + 0,4×5 = 2,4 + 2,0 = 4,4.",
    fonte: { material: "gabarito_prova", capitulo: "Q28" },
    tempoEstimado: 60,
  },
  {
    id: "desemp.cpimedio.b1.001",
    topico: "Desempenho",
    subtopico: "CPI médio",
    dificuldade: 3,
    tipo: "numeric",
    tags: ["cpi", "benchmark"],
    enunciado: "Benchmark B1: ALU 40% (CPI 4), Desvio 30% (CPI 3), Memória 20% (CPI 5), Outras 10% (CPI 6). CPI médio?",
    resposta: { valor: 4.1, base: 10, tolerancia: 0.02 },
    explicacao: "CPI = 0,4×4 + 0,3×3 + 0,2×5 + 0,1×6 = 1,6 + 0,9 + 1,0 + 0,6 = 4,1.",
    fonte: { material: "gabarito_prova", capitulo: "Q29a / P7" },
    tempoEstimado: 90,
  },
  {
    id: "desemp.mips.001",
    topico: "Desempenho",
    subtopico: "Métrica MIPS",
    dificuldade: 3,
    tipo: "numeric",
    tags: ["mips-metrica"],
    enunciado: "Máquina a 200 MHz com CPI médio 8,4. Qual a taxa em MIPS? (MIPS = Freq/(CPI×10⁶))",
    resposta: { valor: 23.8, base: 10, tolerancia: 0.1 },
    explicacao: "MIPS = 200×10⁶ / (8,4 × 10⁶) = 200/8,4 ≈ 23,8.",
    fonte: { material: "gabarito_prova", capitulo: "P12" },
    tempoEstimado: 75,
  },
  {
    id: "desemp.tempo.001",
    topico: "Desempenho",
    subtopico: "Tempo de CPU",
    dificuldade: 4,
    tipo: "numeric",
    tags: ["cpu-time"],
    enunciado: "10000 instruções, CPI 8,4, clock 200 MHz. Qual o tempo em microssegundos (µs)?",
    resposta: { valor: 420, base: 10, tolerancia: 1 },
    explicacao: "Tempo = 10000 × 8,4 / 200×10⁶ = 84000/2×10⁸ = 4,2×10⁻⁴ s = 420 µs.",
    fonte: { material: "gabarito_prova", capitulo: "P11" },
    tempoEstimado: 90,
  },
];
