// Funções MIPS: convenção de chamada, jal/jr, pilha.
// Fonte: slides_mips_funcoes, Lista 3 (Q1).
export default [
  {
    id: "func.jal.001",
    topico: "Funções MIPS",
    subtopico: "Chamada e retorno",
    dificuldade: 2,
    tipo: "single-choice",
    tags: ["jal", "chamada"],
    enunciado: "Qual instrução chama uma função E salva o endereço de retorno em $ra?",
    opcoes: [
      { id: "a", label: "jal label" },
      { id: "b", label: "j label" },
      { id: "c", label: "jr $ra" },
      { id: "d", label: "beq $a0, $a1, label" },
    ],
    resposta: "a",
    explicacao: "jal (jump and link) salta para a função e grava o endereço de retorno em $ra automaticamente.",
    porqueErros: {
      b: "j salta sem salvar retorno.",
      c: "jr é usado para RETORNAR (volta ao endereço em $ra).",
      d: "beq é desvio condicional, não chamada.",
    },
    fonte: { material: "slides_mips_funcoes", capitulo: "jal/jr" },
    tempoEstimado: 30,
  },
  {
    id: "func.args.001",
    topico: "Funções MIPS",
    subtopico: "Convenção de chamada",
    dificuldade: 1,
    tipo: "single-choice",
    tags: ["argumentos", "convencao"],
    enunciado: "Em quais registradores os argumentos de uma função são passados (por convenção)?",
    opcoes: [
      { id: "a", label: "$a0–$a3" },
      { id: "b", label: "$v0–$v1" },
      { id: "c", label: "$t0–$t7" },
      { id: "d", label: "$s0–$s7" },
    ],
    resposta: "a",
    explicacao: "Argumentos vão em $a0–$a3; o resto, na pilha.",
    porqueErros: {
      b: "$v0–$v1 guardam VALORES DE RETORNO.",
      c: "$t0–$t7 são temporários (não preservados).",
      d: "$s0–$s7 são salvos (variáveis preservadas pela função).",
    },
    fonte: { material: "slides_mips_funcoes", capitulo: "Convenção" },
    tempoEstimado: 25,
  },
  {
    id: "func.retorno.001",
    topico: "Funções MIPS",
    subtopico: "Valor de retorno",
    dificuldade: 1,
    tipo: "single-choice",
    tags: ["retorno", "v0"],
    enunciado: "Onde uma função coloca o valor de retorno (ex.: o quadrado de um número)?",
    opcoes: [
      { id: "a", label: "$v0" },
      { id: "b", label: "$a0" },
      { id: "c", label: "$ra" },
      { id: "d", label: "$sp" },
    ],
    resposta: "a",
    explicacao: "O valor de retorno vai em $v0 (e $v1 se precisar de 64 bits).",
    porqueErros: {
      a: "",
      b: "$a0 é argumento de ENTRADA.",
      c: "$ra é o endereço de retorno (para onde voltar), não o valor.",
      d: "$sp é o ponteiro de pilha.",
    },
    fonte: { material: "slides_mips_funcoes", capitulo: "Retorno" },
    tempoEstimado: 25,
  },
  {
    id: "func.seq.001",
    topico: "Funções MIPS",
    subtopico: "Sequência de chamada",
    dificuldade: 3,
    tipo: "order-blocks",
    tags: ["chamada", "ordem"],
    enunciado: "Ordene os passos para chamar uma função quadrado(x) e usar o resultado:",
    opcoes: [
      { id: "args", label: "Colocar x em $a0" },
      { id: "jal", label: "jal quadrado" },
      { id: "ler", label: "Ler o resultado de $v0" },
    ],
    resposta: ["args", "jal", "ler"],
    explicacao: "Primeiro carrega o argumento em $a0, depois jal salta/salva retorno, e só então lê $v0.",
    fonte: { material: "slides_mips_funcoes", capitulo: "Sequência" },
    tempoEstimado: 50,
  },
  {
    id: "func.pilha.001",
    topico: "Funções MIPS",
    subtopico: "Pilha",
    dificuldade: 2,
    tipo: "single-choice",
    tags: ["pilha", "stack"],
    enunciado: "Para abrir espaço na pilha antes de chamar outra função, o que se faz com $sp?",
    opcoes: [
      { id: "a", label: "addi $sp, $sp, -N  (decrementa: a pilha cresce para baixo)" },
      { id: "b", label: "addi $sp, $sp, +N  (incrementa)" },
      { id: "c", label: "Nada, $sp nunca muda" },
      { id: "d", label: "Zerar $sp" },
    ],
    resposta: "a",
    explicacao: "A pilha cresce para endereços menores; abrir espaço = subtrair de $sp. Ao final, soma de volta.",
    porqueErros: {
      b: "Incrementar $sp FECHA espaço (faz ao retornar), não abre.",
      c: "É preciso reservar espaço para salvar $ra e registradores.",
      d: "Zerar $sp destruiria a pilha inteira.",
    },
    fonte: { material: "slides_mips_funcoes", capitulo: "Pilha" },
    tempoEstimado: 45,
  },
];
