// Pipeline MIPS de 5 estágios e hazards.
// Fonte: slides_datapath, Lista 3 (Q4).
export default [
  {
    id: "pipe.estagios.ordem.001",
    topico: "Pipeline",
    subtopico: "Estágios",
    dificuldade: 2,
    tipo: "order-blocks",
    tags: ["pipeline", "estagios"],
    enunciado: "Coloque os 5 estágios do pipeline MIPS na ordem correta:",
    opcoes: [
      { id: "WB", label: "WB (Write Back)" },
      { id: "IF", label: "IF (Instruction Fetch)" },
      { id: "MEM", label: "MEM (Memória)" },
      { id: "ID", label: "ID (Decode)" },
      { id: "EX", label: "EX (Execute)" },
    ],
    resposta: ["IF", "ID", "EX", "MEM", "WB"],
    explicacao: "IF (busca) → ID (decodifica/lê reg) → EX (ULA) → MEM (memória de dados) → WB (escreve reg).",
    fonte: { material: "lista3", capitulo: "Q4" },
    tempoEstimado: 50,
  },
  {
    id: "pipe.mem.001",
    topico: "Pipeline",
    subtopico: "Estágios",
    dificuldade: 1,
    tipo: "single-choice",
    tags: ["pipeline", "MEM"],
    enunciado: "Em qual estágio o pipeline acessa a memória de DADOS (lw/sw)?",
    opcoes: [
      { id: "a", label: "MEM" },
      { id: "b", label: "IF" },
      { id: "c", label: "EX" },
      { id: "d", label: "WB" },
    ],
    resposta: "a",
    explicacao: "MEM é o 4º estágio, dedicado ao acesso à memória de dados. IF acessa a memória de INSTRUÇÕES.",
    porqueErros: {
      b: "IF busca a instrução (memória de instruções).",
      c: "EX é onde a ULA opera/calcula o endereço.",
      d: "WB escreve o resultado no registrador.",
    },
    fonte: { material: "lista3", capitulo: "Q4" },
    tempoEstimado: 25,
  },
  {
    id: "pipe.ex.001",
    topico: "Pipeline",
    subtopico: "Estágios",
    dificuldade: 1,
    tipo: "single-choice",
    tags: ["pipeline", "EX"],
    enunciado: "Em qual estágio a ULA executa a operação aritmética?",
    opcoes: [
      { id: "a", label: "EX" },
      { id: "b", label: "ID" },
      { id: "c", label: "MEM" },
      { id: "d", label: "WB" },
    ],
    resposta: "a",
    explicacao: "EX (Execute) é o estágio da ULA.",
    porqueErros: {
      b: "ID decodifica e lê registradores.",
      c: "MEM acessa memória de dados.",
      d: "WB escreve no banco de registradores.",
    },
    fonte: { material: "lista3", capitulo: "Q4" },
    tempoEstimado: 20,
  },
  {
    id: "pipe.loaduse.001",
    topico: "Pipeline",
    subtopico: "Hazards",
    dificuldade: 4,
    tipo: "single-choice",
    tags: ["hazard", "load-use", "forwarding"],
    enunciado: "Um hazard de load-use (um lw seguido de uma instrução que usa o dado) exige:",
    contexto: "lw $t0, 0($s0)\nadd $t1, $t0, $t2",
    opcoes: [
      { id: "a", label: "Pelo menos 1 bolha (stall) — forwarding sozinho não resolve" },
      { id: "b", label: "Nada, o forwarding resolve sem custo" },
      { id: "c", label: "Descartar (flush) as duas instruções" },
      { id: "d", label: "Trocar lw por sw" },
    ],
    resposta: "a",
    explicacao: "O dado do lw só fica pronto no fim de MEM; a instrução seguinte precisa dele em EX. Mesmo com forwarding, é preciso 1 bolha.",
    porqueErros: {
      b: "Diferente de um hazard ALU-ALU: aqui o forwarding não chega a tempo.",
      c: "Flush é para hazards de controle (desvios), não de dados.",
      d: "Trocar a instrução muda o programa; não é solução de hazard.",
    },
    fonte: { material: "slides_datapath", capitulo: "Hazards" },
    tempoEstimado: 70,
  },
  {
    id: "pipe.predict.001",
    topico: "Pipeline",
    subtopico: "Execução de instruções",
    dificuldade: 3,
    tipo: "predict-output",
    tags: ["predict", "registrador"],
    enunciado: "Com forwarding (sem mudar a lógica), qual o valor final de $t2 (decimal)?",
    contexto: "addi $t0, $zero, 5\naddi $t1, $zero, 3\nadd  $t2, $t0, $t1\nsub  $t2, $t2, $t1",
    resposta: { valor: 5, base: 10, tolerancia: 0, alvo: "$t2" },
    explicacao: "$t0=5, $t1=3, $t2=5+3=8, depois $t2=8−3=5. O forwarding garante valores corretos.",
    fonte: { material: "slides_datapath", capitulo: "Forwarding" },
    tempoEstimado: 75,
  },
];
