import type { ExamBlueprint } from '../types/content';

export const reavaliacaoBlueprint: ExamBlueprint = {
  id: 'reavaliacao-aeds-2-v1',
  title: 'Simulado de Reavaliacao AEDS II',
  questions: [
    {
      id: 'q1-somatorio',
      number: 1,
      domainId: 'somatorio',
      format: 'summation-from-code',
      title: 'Somatorio a partir de codigo',
      stem: 'Considere um trecho com dois lacos: i varia de 1 ate n - 1 e j varia de 0 ate i - 1.',
      steps: [
        {
          id: 'simulado-somatorio-identificar',
          kind: 'choice',
          skillId: 'recognize',
          prompt: 'Qual custo assintotico nasce da contagem total do laco interno?',
          correctOptionId: 'quadratico',
          options: [
            { id: 'quadratico', label: 'O(n^2)' },
            { id: 'linear', label: 'O(n)', mistakeTag: 'wrong-summation-bound' },
            { id: 'logaritmico', label: 'O(log n)', mistakeTag: 'wrong-summation-bound' },
          ],
          explanation: 'A soma 1 + 2 + ... + (n - 1) cresce quadraticamente.',
        },
        {
          id: 'simulado-somatorio-formula',
          kind: 'code',
          skillId: 'justify',
          prompt: 'Digite a formula fechada para 1 + 2 + ... + (n - 1).',
          acceptedAnswers: ['n * (n - 1) / 2', '(n * (n - 1)) / 2'],
          mistakeTag: 'wrong-summation-bound',
          explanation: 'A soma dos inteiros de 1 ate n - 1 e n(n - 1)/2.',
        },
      ],
    },
    {
      id: 'q2-avl',
      number: 2,
      domainId: 'avl',
      format: 'structure-simulation',
      title: 'Simulacao de AVL',
      stem: 'Insira 10, 20 e 30 em uma AVL inicialmente vazia.',
      steps: [
        {
          id: 'simulado-avl-rotacao',
          kind: 'choice',
          skillId: 'simulate',
          prompt: 'Depois de inserir 30, qual correcao reequilibra a raiz?',
          correctOptionId: 'rotacao-simples-esquerda',
          options: [
            { id: 'rotacao-simples-esquerda', label: 'Rotacao simples para a esquerda' },
            { id: 'rotacao-simples-direita', label: 'Rotacao simples para a direita', mistakeTag: 'wrong-rotation' },
            { id: 'rotacao-dupla', label: 'Rotacao dupla', mistakeTag: 'wrong-rotation' },
          ],
          explanation: 'A sequencia 10, 20, 30 cria caso RR, corrigido com rotacao simples a esquerda.',
        },
        {
          id: 'simulado-avl-fator',
          kind: 'gap',
          skillId: 'recognize',
          prompt: 'Antes da rotacao, qual e o fator de balanceamento da raiz 10 usando altura(esq) - altura(dir)?',
          answers: ['-2'],
          mistakeTag: 'wrong-rotation',
          explanation: 'A subarvore direita tem dois niveis a mais, entao o fator fica -2.',
        },
      ],
    },
    {
      id: 'q3-trie',
      number: 3,
      domainId: 'trie',
      format: 'prove-or-refute',
      title: 'Provar ou refutar em TRIE',
      stem: 'Uma TRIE contem a palavra casa. Analise a afirmacao: se cas existe como prefixo, entao cas tambem e palavra.',
      steps: [
        {
          id: 'simulado-trie-prefixo',
          kind: 'rubric',
          skillId: 'justify',
          prompt: 'Escolha uma justificativa aceitavel para a afirmacao.',
          acceptableOptionIds: ['falso-marca-fim'],
          options: [
            { id: 'falso-marca-fim', label: 'Falsa: precisa haver marcador de fim em cas.' },
            { id: 'verdade-prefixo', label: 'Verdadeira: todo prefixo armazenado e palavra.', mistakeTag: 'prefix-vs-word' },
            { id: 'depende-alfabeto', label: 'Depende apenas do tamanho do alfabeto.', mistakeTag: 'wrong-case-analysis' },
          ],
          explanation: 'Prefixo percorrivel nao basta; palavra completa exige marcador de fim.',
        },
        {
          id: 'simulado-trie-custo',
          kind: 'code',
          skillId: 'justify',
          prompt: 'Digite o custo de pesquisar uma palavra de tamanho k em uma TRIE.',
          acceptedAnswers: ['O(k)', 'Theta(k)', 'k'],
          mistakeTag: 'prefix-vs-word',
          explanation: 'A busca percorre no maximo um no por caractere da palavra.',
        },
      ],
    },
    {
      id: 'q4-ordenacao',
      number: 4,
      domainId: 'ordenacao',
      format: 'algorithm-adaptation',
      title: 'Adaptacao de algoritmo de ordenacao',
      stem: 'Adapte a insercao para colocar a chave atual na posicao correta em um prefixo ja ordenado.',
      steps: [
        {
          id: 'simulado-ordenacao-blocos',
          kind: 'blocks',
          skillId: 'program',
          prompt: 'Ordene os blocos da insercao.',
          blocks: [
            { id: 'insert', label: 'coloque chave em j + 1' },
            { id: 'compare', label: 'enquanto j >= 0 e vetor[j] > chave' },
            { id: 'scan', label: 'guarde vetor[i] em chave e faca j = i - 1' },
            { id: 'shift', label: 'desloque vetor[j] para j + 1 e decremente j' },
          ],
          correctOrder: ['scan', 'compare', 'shift', 'insert'],
          mistakeTag: 'algorithm-confusion',
          explanation: 'Insertion sort guarda a chave, desloca maiores e insere a chave na abertura.',
        },
        {
          id: 'simulado-ordenacao-caso',
          kind: 'choice',
          skillId: 'justify',
          prompt: 'No pior caso da insercao simples, qual e o custo?',
          correctOptionId: 'pior-quadratico',
          options: [
            { id: 'pior-quadratico', label: 'O(n^2)' },
            { id: 'sempre-linear', label: 'O(n)', mistakeTag: 'wrong-case-analysis' },
            { id: 'sempre-log', label: 'O(log n)', mistakeTag: 'algorithm-confusion' },
          ],
          explanation: 'Em ordem reversa, cada chave pode deslocar quase todo o prefixo.',
        },
      ],
    },
    {
      id: 'q5-arvore',
      number: 5,
      domainId: 'arvore',
      format: 'case-analysis',
      title: 'Melhor e pior caso em arvore normal',
      stem: 'Analise uma funcao recursiva que calcula altura visitando esquerda e direita.',
      steps: [
        {
          id: 'simulado-arvore-caso-base',
          kind: 'code',
          skillId: 'program',
          prompt: 'Digite o retorno correto para o caso base de um ponteiro nulo.',
          acceptedAnswers: ['return 0', '0'],
          mistakeTag: 'missing-base-case',
          explanation: 'Em altura por numero de nos, subarvore vazia contribui com 0.',
        },
        {
          id: 'simulado-arvore-rubrica',
          kind: 'rubric',
          skillId: 'justify',
          prompt: 'Por que o custo e O(n) quando a funcao calcula altura de toda a arvore?',
          acceptableOptionIds: ['visita-todos'],
          options: [
            { id: 'visita-todos', label: 'Porque cada no real e visitado uma vez.' },
            { id: 'so-altura', label: 'Porque sempre percorre so a altura.', mistakeTag: 'wrong-case-analysis' },
            { id: 'regra-abb', label: 'Porque aplica a regra de busca de ABB.', mistakeTag: 'algorithm-confusion' },
          ],
          explanation: 'A funcao precisa combinar a altura das duas subarvores em todos os nos.',
        },
      ],
    },
    {
      id: 'q6-doidona',
      number: 6,
      domainId: 'doidona',
      format: 'composite-structure-method',
      title: 'Metodo em Estrutura Doidona',
      stem: 'Implemente a busca em uma estrutura composta por T1, T2, T3, lista e arvore.',
      steps: [
        {
          id: 'simulado-doidona-camada',
          kind: 'fix',
          skillId: 'program',
          prompt: 'A busca abaixo retorna falso antes de verificar todas as camadas. Corrija a linha problematica.',
          lines: ['if (estaNaT1(x)) return true;', 'return false;', 'return pesquisarT2T3ListaArvore(x);'],
          correctLineIndex: 1,
          fixOptions: [
            { id: 'buscar-restante', label: 'trocar por busca nas outras camadas' },
            { id: 'parar', label: 'manter retorno falso', mistakeTag: 'incomplete-layer-search' },
          ],
          correctFixId: 'buscar-restante',
          explanation: 'A busca so pode falhar depois de testar todas as estruturas auxiliares.',
        },
        {
          id: 'simulado-doidona-ordem',
          kind: 'blocks',
          skillId: 'simulate',
          prompt: 'Ordene uma estrategia segura de pesquisa na estrutura composta.',
          blocks: [
            { id: 'arvore', label: 'pesquisar na arvore' },
            { id: 't2', label: 'pesquisar em T2' },
            { id: 'lista', label: 'percorrer lista' },
            { id: 't1', label: 'testar posicao em T1' },
            { id: 't3', label: 'pesquisar em T3' },
          ],
          correctOrder: ['t1', 't2', 't3', 'lista', 'arvore'],
          mistakeTag: 'incomplete-layer-search',
          explanation: 'A ordem documenta todas as camadas antes de concluir ausencia.',
        },
      ],
    },
  ],
};
