import type { PracticeVariation } from '../types/content';

export const reviewVariations: PracticeVariation[] = [
  {
    id: 'review-somatorio-limites-1',
    domainId: 'somatorio',
    skillId: 'recognize',
    questionFormat: 'summation-from-code',
    targetMistakeTag: 'wrong-summation-bound',
    title: 'Limites de somatorio',
    prompt: 'Refaca a contagem para i de 0 ate n - 1 e j de i + 1 ate n - 1.',
  },
  {
    id: 'review-avl-rotacao-1',
    domainId: 'avl',
    skillId: 'simulate',
    questionFormat: 'structure-simulation',
    targetMistakeTag: 'wrong-rotation',
    title: 'Rotacao AVL parecida',
    prompt: 'Insira 30, 10 e 20 e escolha entre rotacao simples ou dupla.',
  },
  {
    id: 'review-trie-prefixo-1',
    domainId: 'trie',
    skillId: 'justify',
    questionFormat: 'prove-or-refute',
    targetMistakeTag: 'prefix-vs-word',
    title: 'Prefixo contra palavra',
    prompt: 'Explique por que "car" pode existir como caminho sem ser palavra quando "carta" foi inserida.',
  },
  {
    id: 'review-arvore-base-1',
    domainId: 'arvore',
    skillId: 'program',
    questionFormat: 'case-analysis',
    targetMistakeTag: 'missing-base-case',
    title: 'Caso base recursivo',
    prompt: 'Complete o caso base de uma funcao que conta folhas em uma arvore binaria.',
  },
  {
    id: 'review-doidona-camadas-1',
    domainId: 'doidona',
    skillId: 'program',
    questionFormat: 'composite-structure-method',
    targetMistakeTag: 'incomplete-layer-search',
    title: 'Busca em todas as camadas',
    prompt: 'Reescreva a pesquisa para continuar depois de falhar em T1.',
  },
  {
    id: 'review-doidona-ponteiro-1',
    domainId: 'doidona',
    skillId: 'program',
    questionFormat: 'composite-structure-method',
    targetMistakeTag: 'lost-pointer',
    title: 'Religar ponteiro',
    prompt: 'Escolha a linha que preserva o proximo no ao inserir no meio da lista.',
  },
  {
    id: 'review-ordenacao-caso-1',
    domainId: 'ordenacao',
    skillId: 'justify',
    questionFormat: 'algorithm-adaptation',
    targetMistakeTag: 'wrong-case-analysis',
    title: 'Melhor e pior caso',
    prompt: 'Compare insertion sort em vetor quase ordenado e em vetor reverso.',
  },
  {
    id: 'review-ordenacao-confusao-1',
    domainId: 'ordenacao',
    skillId: 'program',
    questionFormat: 'algorithm-adaptation',
    targetMistakeTag: 'algorithm-confusion',
    title: 'Selecao ou insercao',
    prompt: 'Identifique qual bloco pertence ao selection sort e qual pertence ao insertion sort.',
  },
];
